name: corn_disease_detection
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  tflite_flutter: ^0.11.0  # Updated version
  image: ^4.1.3  # Updated version for compatibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/models/best_int8.tflite
    - assets/translations/en.json
    - assets/translations/tl.json
    - assets/translations/ceb.json
    - assets/images/Logo.png
    - assets/images/Usericon.png
    - assets/images/FarmImage.png
    - assets/images/search.png
    - assets/images/Home.png
    - assets/images/ScanNavBar.png
    - assets/images/DiagnosIcon.png
    - assets/images/CommonRust.png
    - assets/images/rustImage.png
    - assets/images/phaeosphaeriaImage.png
    - assets/images/northern_leaf_blightImage.png
    - assets/images/
    - assets/models/
    - assets/i18n/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"  # Update this path as well
  min_sdk_android: 21 # android min sdk min:16, default 21
